### ISSUE TITLE
Feature requests / bug reports for Cloudflare, Inc.

### ISSUE THREAD

**Issue by wenbinf** [microfeed/microfeed#3]
## Overall
- [ ] OAuth Login with Cloudflare and grant permissions via Cloudflare UI. In this way, we may not need GitHub Secrets & Actions. We can do (almost) one-click deployment completely via Cloudflare. 
- [ ] A central place to get Cloudflare account id, api token, and r2 api token. [Right now it's quite tricky to all these things on multiple Cloudflare webpages](https://github.com/microfeed/microfeed#step-2-put-some-secrets-on-your-forked-repo).

## Pages
- [ ] API (or wrangler2) to check if the name of a new Pages project is legal / unique. https://github.com/microfeed/microfeed/issues/7
- [ ] more informative error 1101 page than "you should login to Cloudflare and check the error logs for ..."

## R2
- [ ] Allows to programmatically make a R2 bucket public via Cloudflare API (or S3-compatible API): https://github.com/microfeed/microfeed/blob/main/ops/init_r2.js#L24
- [ ] API (or wrangler2) to update CORS settings of a public bucket. Right now we use S3-compatible API: https://github.com/microfeed/microfeed/blob/main/ops/init_r2.js#L44
- [ ] API (or wrangler2) to check if R2 ids/tokens are valid. https://github.com/microfeed/microfeed/issues/38

## D1
- [ ] API to get D1 uuid, or allow to bind D1's human-readable name to a Pages project instead of using uuid. 
- [x] Make this work in production - "If record exists, update; else insert". Currently we have to do a hack "update AND insert": https://github.com/microfeed/microfeed/blob/main/edge-src/models/FeedDb.js#L358

## Zero Trust
- [ ] Don't show error message "the zone does not exist" when adding *.pages.dev in Zero Trust Self-Hosted Application.  https://github.com/microfeed/microfeed/issues/20#issuecomment-1367906409
- [ ] Don't disallow editing path when adding *.pages.dev. It's very confusing. 
- [ ] An easy way to refresh jwt token? This is relate to an issue: POST ajax requests won't refresh jwt token.

**Comment by Kamariw95** [comment]
Extremely smart to do this.

**Comment by Tessy247** [comment]
- [ ] I don't understand

**Comment by codehz** [comment]
> * Make this work in production - "If record exists, update; else insert". Currently we have to do a hack "update AND insert": https://github.com/microfeed/microfeed/blob/main/edge-src/models/FeedDb.js#L358

Is it possible to do this with [upsert](https://www.sqlite.org/lang_upsert.html) trick?

**Comment by Suleman-Elahi** [comment]
What about adding Sitemap for submitting the website to search engines?

**Comment by wenbinf** [comment]
> > * Make this work in production - "If record exists, update; else insert". Currently we have to do a hack "update AND insert": https://github.com/microfeed/microfeed/blob/main/edge-src/models/FeedDb.js#L358
> 
> Is it possible to do this with [upsert](https://www.sqlite.org/lang_upsert.html) trick?

@codehz Thanks for the tip! Done: https://github.com/microfeed/microfeed/pull/57

**Comment by wenbinf** [comment]
> What about adding Sitemap for submitting the website to search engines?

@Suleman-Elahi Good call. It's added to the "Ideas" https://github.com/microfeed/microfeed/discussions/58
Hopefully we'll get to that soon. Or if anyone wants to do it and send a pull request - it's an open-source project after all :)
